require('dotenv').config()

const TWITCH_CLIENT_ID = process.env.TWITCH_CLIENT_ID
const TWITCH_SECRET = process.env.TWTICH_SECRET
const TWITCH_CALLBACK_URL = process.env.CALLBACK_URL
const TWITCH_AUTHORIZED_ENDPOINT = process.env.TWITCH_AUTHORIZED_ENDPOINT
const TWITCH_ENDPOINT = process.env.TWITCH_ENDPOINT

const SESSION_SECRET = process.env.SESSION_SECRET

module.exports = {
  TWITCH_CLIENT_ID,
  TWITCH_SECRET,
  TWITCH_CALLBACK_URL,
  TWITCH_AUTHORIZED_ENDPOINT,
  TWITCH_ENDPOINT,
  SESSION_SECRET
}